import type { NewBoat } from "./schema";

/**
 * Single source of truth for dev seed data.
 *
 * Used by:
 *  - POST /api/dev/reset            (dev console "Reset database")
 *  - scripts/generate-seed-sql.ts   (regenerates scripts/seed.sql for the CLI)
 *
 * After editing, run: npm run db:seed:generate
 */
export const seedBoats: NewBoat[] = [
  {
    id: "solstice",
    name: "Solstice",
    type: "Sailing yacht",
    length: "42 ft",
    location: "Lefkada, Greece",
    country: "Greece",
    region: "Mediterranean",
    dates: "12 Sep – 4 Oct",
    dateStart: "2026-09-12",
    dateEnd: "2026-10-04",
    duration: "22 nights",
    nights: 22,
    image:
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1566847438217-76e82d383f84?auto=format&fit=crop&w=900&q=85",
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=85",
    ],
    owner: "Maya & Finn",
    ownerImage: "https://i.pravatar.cc/160?img=47",
    rating: 4.9,
    reviews: 18,
    applicants: 6,
    description:
      "Solstice is our much-loved bluewater cruiser, tucked into a quiet marina on Lefkada. We need a confident liveaboard to keep her aired, secure and happy while we visit family.",
    home: "Private aft cabin, full galley and a bright saloon. The marina has showers, laundry, a pool and tavernas a short walk away.",
    responsibilities: [
      "Check bilges and battery monitor each morning",
      "Run engine and watermaker weekly",
      "Adjust lines and fenders after strong weather",
      "Flush heads and air cabins regularly",
    ],
    systems: ["Yanmar diesel", "12V / solar", "Watermaker", "Electric windlass"],
    requirements: ["5+ years sailing", "Diesel basics", "Liveaboard experience"],
    amenities: ["Shore power", "Wi-Fi", "Tender", "Paddleboard", "Air conditioning"],
    pet: "Pip, a sea-loving terrier",
    featured: true,
    published: true,
  },
  {
    id: "blue-hour",
    name: "Blue Hour",
    type: "Catamaran",
    length: "46 ft",
    location: "St. George's, Grenada",
    country: "Grenada",
    region: "Caribbean",
    dates: "3 Nov – 1 Dec",
    dateStart: "2026-11-03",
    dateEnd: "2026-12-01",
    duration: "28 nights",
    nights: 28,
    image:
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    owner: "Jonas",
    ownerImage: "https://i.pravatar.cc/160?img=12",
    rating: 5,
    reviews: 11,
    applicants: 9,
    description:
      "A spacious Lagoon catamaran on a sheltered mooring. Ideal for a couple who know tropical weather routines and are comfortable using a dinghy.",
    home: "Owner's hull, island galley, water views from every window and reliable marina Wi-Fi.",
    responsibilities: [
      "Daily mooring and chafe inspection",
      "Monitor solar, batteries and fridge",
      "Start both engines weekly",
      "Secure deck before squalls",
    ],
    systems: ["Twin Yanmar diesels", "Lithium bank", "Solar array", "Dinghy outboard"],
    requirements: ["Catamaran experience", "Dinghy handling", "Storm awareness"],
    amenities: ["Wi-Fi", "Kayaks", "Tender", "BBQ", "Washer"],
    pet: null,
    featured: false,
    published: true,
  },
  {
    id: "northern-light",
    name: "Northern Light",
    type: "Motor yacht",
    length: "38 ft",
    location: "Bergen, Norway",
    country: "Norway",
    region: "Northern Europe",
    dates: "5 Jan – 2 Feb",
    dateStart: "2027-01-05",
    dateEnd: "2027-02-02",
    duration: "28 nights",
    nights: 28,
    image:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1400&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1520645521318-f03a712f0e67?auto=format&fit=crop&w=900&q=85",
    ],
    owner: "Ingrid",
    ownerImage: "https://i.pravatar.cc/160?img=32",
    rating: 4.7,
    reviews: 6,
    applicants: 3,
    description:
      "Winter berth in a working harbour. The job is mostly about heat, humidity and shore power — she must not be left to freeze.",
    home: "Heated saloon with a diesel stove, compact galley, and a short walk into town.",
    responsibilities: [
      "Verify shore power and heater daily",
      "Check for ice around the hull",
      "Run dehumidifier and log readings",
      "Clear snow from decks and covers",
    ],
    systems: ["Volvo Penta diesel", "Diesel heater", "Shore power", "Dehumidifier"],
    requirements: ["Cold weather experience", "Comfortable alone", "Basic electrics"],
    amenities: ["Shore power", "Wi-Fi", "Heating", "Bicycle"],
    pet: null,
    featured: false,
    published: true,
  },
  {
    id: "kingfisher",
    name: "Kingfisher",
    type: "Sailing yacht",
    length: "36 ft",
    location: "Whangarei, New Zealand",
    country: "New Zealand",
    region: "South Pacific",
    dates: "18 Feb – 20 Mar",
    dateStart: "2027-02-18",
    dateEnd: "2027-03-20",
    duration: "30 nights",
    nights: 30,
    image:
      "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    owner: "Tama & Ruth",
    ownerImage: "https://i.pravatar.cc/160?img=68",
    rating: 4.8,
    reviews: 24,
    applicants: 12,
    description:
      "Our steel ketch sits on a quiet river mooring while we head to the South Island. Cyclone season, so weather awareness matters more than sailing miles.",
    home: "Full run of the boat, wood stove, and a dinghy for the short row ashore.",
    responsibilities: [
      "Check mooring bridle for chafe weekly",
      "Monitor forecast for cyclone activity",
      "Run engine and charge batteries",
      "Ventilate to keep damp down",
    ],
    systems: ["Ford Lehman diesel", "Wind generator", "Solar", "Wood stove"],
    requirements: ["Anchoring experience", "Weather routing", "Dinghy handling"],
    amenities: ["Wi-Fi", "Tender", "Bicycle", "Wood stove"],
    pet: "Two cats, Rigging and Halyard",
    featured: true,
    published: true,
  },
  {
    id: "saltwood",
    name: "Saltwood",
    type: "Classic sloop",
    length: "31 ft",
    location: "Falmouth, England",
    country: "United Kingdom",
    region: "Northern Europe",
    dates: "1 Apr – 15 Apr",
    dateStart: "2027-04-01",
    dateEnd: "2027-04-15",
    duration: "14 nights",
    nights: 14,
    image:
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    owner: "Peter",
    ownerImage: "https://i.pravatar.cc/160?img=59",
    rating: 4.6,
    reviews: 9,
    applicants: 2,
    description:
      "A wooden sloop on a pontoon berth. She needs someone patient who understands that a timber hull wants watching, not fixing.",
    home: "Snug forepeak berth, kettle, and the sailing club showers two minutes away.",
    responsibilities: [
      "Check bilge twice daily — she takes up slowly",
      "Inspect topside seams after dry spells",
      "Tend lines on spring tides",
      "Keep her covered and aired",
    ],
    systems: ["Beta 20 diesel", "12V system", "Manual bilge pump"],
    requirements: ["Wooden boat experience preferred", "Tidal berth awareness"],
    amenities: ["Shore power", "Wi-Fi", "Club facilities"],
    pet: null,
    featured: false,
    published: true,
  },
];
